# Generated by Django 3.2.6 on 2021-08-31 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipl', '0001_alter_match_toss_decision'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveries',
            name='bowler',
            field=models.CharField(default='', max_length=100),
        ),
    ]
