version: '3'

services:
  db:
    image: postgres:11-alpine
    restart: always
    environment:
      - POSTGRES_DB=postgres1
      - POSTGRES_USER=postgres1
      - POSTGRES_PASSWORD=postgres1
    ports:
      - "5432:5432"
  django:
    build: ./api
    restart: always
    command : bash -c "python manage.py migrate && python manage.py load_match &&
                  python manage.py runserver 0.0.0.0:8000" 
    volumes:
      - ./api:/app/api
    ports:
      - "8000:8000"
    depends_on:
      - db