# Generated by Django 3.2.6 on 2021-08-30 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('season', models.CharField(max_length=100)),
                ('team1', models.CharField(max_length=100)),
                ('team2', models.CharField(max_length=100)),
                ('toss_winner', models.CharField(max_length=100)),
                ('toss_decision', models.PositiveIntegerField(choices=[(1, 'field'), (2, 'bat')], editable=False)),
                ('result', models.CharField(max_length=100)),
                ('dl_applied', models.BooleanField(default=False)),
                ('winner', models.CharField(max_length=100)),
                ('win_by_runs', models.PositiveIntegerField(editable=False)),
                ('win_by_wickets', models.PositiveIntegerField(editable=False)),
                ('player_of_match', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=1024)),
                ('umpire1', models.CharField(max_length=100)),
                ('umpire2', models.CharField(max_length=100)),
                ('umpire3', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Deliveries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inning', models.PositiveIntegerField(editable=False)),
                ('batting_team', models.CharField(max_length=100)),
                ('bowling_team', models.CharField(max_length=100)),
                ('over', models.PositiveIntegerField(editable=False)),
                ('ball', models.PositiveIntegerField(editable=False)),
                ('batsman', models.CharField(max_length=100)),
                ('non_striker', models.CharField(max_length=100)),
                ('is_super_over', models.BooleanField(default=False)),
                ('wide_runs', models.PositiveIntegerField(editable=False)),
                ('bye_runs', models.PositiveIntegerField(editable=False)),
                ('legbye_runs', models.PositiveIntegerField(editable=False)),
                ('noball_runs', models.PositiveIntegerField(editable=False)),
                ('penalty_runs', models.PositiveIntegerField(editable=False)),
                ('batsman_runs', models.PositiveIntegerField(editable=False)),
                ('extra_runs', models.PositiveIntegerField(editable=False)),
                ('total_runs', models.PositiveIntegerField(editable=False)),
                ('player_dismissed', models.CharField(max_length=100)),
                ('dismissal_kind', models.CharField(max_length=100)),
                ('fielder', models.CharField(max_length=100)),
                ('match', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='ipl.match')),
            ],
        ),
    ]
