
# DATABASES = {'default': {'ENGINE': 'django.db.backends.postgresql_psycopg2',
#   'USER': 'ipl',
#   'PASSWORD': 'ipl',
#   'EXTRAS': '',
#   'NAME': 'ipl',
#   'HOST': 'localhost',
#   'PORT': '5432',
#   'ATOMIC_REQUESTS': False,
#   'AUTOCOMMIT': True,
#   'CONN_MAX_AGE': 0,
#   'OPTIONS': {},
#   'TIME_ZONE': None,
#   'TEST': {'CHARSET': None, 'COLLATION': None, 'NAME': None, 'MIRROR': None}},
#  'OPTIONS': {'threaded': True}}
